mediatheque_homepage:
    path:     /
    defaults: { _controller: mediathequeBundle:Default:index }
    
mediatheque_nouveaute:
    path:    /nouveaute
    defaults: { _controller: mediathequeBundle:Default:listebd }
    
mediatheque_evenements:
    path:    /evenements
    
mediatheque_reservation:
    path:    /reservation
    defaults: {_controller: mediathequeBundle:Default:reservation }