mediatheque_homepage:
    path:     /
    defaults: { _controller: mediathequeBundle:Default:index }

mediatheque_nouveaute:
    path:    /nouveaute
    defaults: { _controller: mediathequeBundle:Default:listenouveaute }

mediatheque_evenements:
    path:    /evenements

mediatheque_reservation:
    path:    /reservation
    defaults: {_controller: mediathequeBundle:Default:reservation }

mediatheque_mesreservations:
    path:    /mesresas
    defaults: {_controller: mediathequeBundle:Default:mesReservations }

mediatheque_adminspace:
    path:    /listeresa
    defaults: {_controller: mediathequeBundle:Default:adminListeResa }

mediatheque_confirmemprunt:
    path:    /confirmemprunt
    defaults: {_controller: mediathequeBundle:Default:Emprunt }
